### ISSUE TITLE
Add bypass TPM/CPU for Windows 11 optional.

### ISSUE THREAD

**Issue by panther7** [uup-dump/converter#23]
Like: https://github.com/AveYo/MediaCreationTool.bat/blob/main/bypass11/Quick_11_iso_esd_wim_TPM_toggle.bat

**Comment by eladkarako** [comment]
a clear stopping-point, when `AutoStart    =0`
just before the mounted folder gets unmounted,  
would be sufficient,  
this way I'll be able to mount the registry hive to my registry,  
and [apply the patches myself.. ](https://gist.github.com/eladkarako/c593b72d8df7b3d195b10204252bafb3#file-windows-10-windows-11-unrestricted-setup-for-vm-md).  

I currently tested the scripts and they pass right through after applying the latest updates to just unmounting and compressing to esd.. and since there is a massive usage of repeating method in the build process it is hard to pin-point an exact moment in time to do so..

the stopping-point can be as simple as couple of `pause` with notification "this is a good time to see if you want to add files, or mount the registry hive, before we're closing it up to a wim (or esd)."

when users will be done, all they have to do is to press any key and the process would continue, very little code change is needed.  

this way applying patches, installing msi,msu,cab and small modifications can be easily done, without re-packing the end result ISO again.
